services:
  runner:
    image: runner
    build:
      dockerfile: docker/runner.Dockerfile
      target: staging
      context: .
    env_file:
      - .env
    volumes:
      - ./input:/app/input
      - ./logs:/app/logs
      - ./config.json:/config.json
    command: ["run"]

  maildev:
    image: maildev/maildev:2.2.1
    ports:
      - 1080:1080
