"""orange_hrm_errors

Revision ID: 10c23f547a96
Revises: d3ba7c792db6
Create Date: 2026-07-23 18:56:09.906646

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10c23f547a96"
down_revision: Union[str, Sequence[str], None] = "d3ba7c792db6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orange_hrm_errors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("input_item_id", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["portal_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orange_hrm_errors")
    # ### end Alembic commands ###
