"""saucedemo

Revision ID: 73f520dfa6a3
Revises: 10c23f547a96
Create Date: 2026-07-23 19:34:50.135567

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73f520dfa6a3"
down_revision: Union[str, Sequence[str], None] = "10c23f547a96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saucedemo_errors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("input_item_id", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["portal_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "saucedemo_output",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("order_items", sa.Text(), nullable=False),
        sa.Column("order_subtotal", sa.Numeric(), nullable=False),
        sa.Column("order_total", sa.Numeric(), nullable=False),
        sa.Column("order_tax", sa.Numeric(), nullable=False),
        sa.Column("order_shipping_info", sa.String(), nullable=False),
        sa.Column("order_payment_info", sa.String(), nullable=False),
        sa.Column("receipt_filename", sa.String(), nullable=False),
        sa.Column("receipt_body", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["portal_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("saucedemo_output")
    op.drop_table("saucedemo_errors")
    # ### end Alembic commands ###
