"""portal_runs_delete_specifics

Revision ID: af4f68cb4aca
Revises: 4067a3e5a0fe
Create Date: 2026-07-23 01:52:35.581848

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af4f68cb4aca"
down_revision: Union[str, Sequence[str], None] = "4067a3e5a0fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("portal_runs", "unchanged_items")
    op.drop_column("portal_runs", "updated_items")
    op.drop_column("portal_runs", "created_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "portal_runs",
        sa.Column("created_items", sa.INTEGER(), nullable=False),
    )
    op.add_column(
        "portal_runs",
        sa.Column("updated_items", sa.INTEGER(), nullable=False),
    )
    op.add_column(
        "portal_runs",
        sa.Column("unchanged_items", sa.INTEGER(), nullable=False),
    )
    # ### end Alembic commands ###
